[package]
name = "kah"
version = "0.2.0"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
homepage = "https://github.com/sondr3/kah"
description = "A small helper for kattis assignments"
repository = "https://github.com/sondr3/kah"
documentation = "https://github.com/sondr3/kah"
readme = "README.md"
license = "GPL-3.0-or-later"
edition = "2018"

[features]
fail-on-warnings = []

[badges]
travis-ci = { repository = "sondr3/kah" }

[[bin]]
name = "kah"
path = "src/main.rs"

[dependencies]
structopt = "0.3.2"
reqwest = "0.9.21"
zip = "0.5.3"
tempfile = "3.1.0"
rust-ini = "0.13.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
